include:
  - board: nice_nano
    shield: 7skb_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: 7skb_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano
  #   shield: settings_reset
  # - board: nice_nano
  #   shield: sofle_left
  # - board: nice_nano
  #   shield: sofle_right
